import { clsx } from "clsx";

import {
  BriefcaseBusiness,
  Building,
  ChartColumnBig,
  Check,
  Database,
  FilePlus,
  FileSearch2,
  FileText,
  Globe,
  Lightbulb,
  Linkedin,
  ListOrdered,
  Logs,
  Mail,
  MailCheck,
  PieChart,
  PlusCircle,
  RefreshCcw,
  Search,
  Server,
  User,
  UserRoundPlus,
  UsersRound,
  Volume2,
  Headset,
  Phone,
  MessageSquare,
  MessagesSquare,
  ShieldCheck,
  FileCheck,
  BarChart3,
  CalendarClock,
  CreditCard,
  Layers,
  Settings,
  ClipboardCheck,
  Users,
  Activity,
  Workflow,
  Brain,
  Bot,
  Cpu,
  LineChart,
  Gauge,
  Blocks,
  Zap,
} from "lucide-react";

import { twMerge } from "tailwind-merge";

export function cn(...inputs) {
  return twMerge(clsx(inputs));
}

export const KPOSERVICES = [
  {
    icon: Mail,
    title: "Email List Building",
    detailPath: "/kpo-services/email-list-building",
    description: "Targeted lists. Quality leads. Maximum impact.",
    key: "email-list-building",
    color: "purple1",
  },
  {
    icon: PlusCircle,
    title: "Data Append",
    detailPath: "/kpo-services/data-append",
    description: "Enhance accuracy. Fill gaps. Boost insights.",
    key: "data-append",
    color: "purple2",
  },
  {
    icon: RefreshCcw,
    title: "Data Refresh",
    detailPath: "/kpo-services/data-refresh",
    description: "Update. Verify. Stay current.",
    key: "data-refresh",
    color: "purple1",
  },
  {
    icon: Database,
    title: "Customize B2B Database",
    detailPath: "/kpo-services/customize-b2b-database",
    description: "Tailored data. Better targeting. Greater results",
    key: "customize-b2b-database",
    color: "purple2",
  },
  {
    icon: Building,
    title: "DataBase Building",
    detailPath: "/kpo-services/database-building",
    description: "Accurate data. Smart solutions. Stronger connections.",
    key: "database-building",
    color: "purple1",
  },
  {
    icon: FileSearch2,
    detailPath: "/kpo-services/content-research",
    title: "Content Research",
    description: "Insights-driven. Well-crafted. Engaging content.",
    key: "content-research",
    color: "purple2",
  },
  {
    icon: Linkedin,
    title: "LinkedIn Data Search",
    detailPath: "/kpo-services/linkedin-data-search",
    description: "Targeted profiles. Relevant connections. Precise insights.",
    key: "linkedin-data-search",
    color: "purple1",
  },
  {
    icon: Volume2,
    title: "Lead generation",
    detailPath: "/kpo-services/lead-generation",
    description:
      "Qualified leads. Stronger opportunities. Greater conversions.",
    key: "lead-generation",
    color: "purple2",
  },
  {
    icon: Server,
    title: "Online-Offline Data entry Services",
    detailPath: "/kpo-services/online-offline-data",
    description:
      "Fast, accurate, and reliable data input for seamless operations.",
    key: "online-offline-data",
    color: "purple1",
  },
  {
    icon: Check,
    title: "Data-Validation",
    detailPath: "/kpo-services/data-validation",
    description: "Ensure accuracy. Eliminate errors. Strengthen decisions.",
    key: "data-validation",
    color: "purple2",
  },
  {
    icon: PieChart,
    title: "Data-Mining",
    detailPath: "/kpo-services/data-mining",
    description:
      "Extract valuable insights. Uncover patterns. Drive informed decisions.",
    key: "data-mining",
    color: "purple1",
  },
  {
    icon: Globe,
    title: "Web-Research",
    detailPath: "/kpo-services/web-research",
    description: "Optimize content, design, and user experience.",
    key: "web-research",
    color: "purple2",
  },
  {
    icon: Logs,
    title: "List-Research",
    detailPath: "/kpo-services/list-research",
    description:
      "Gathers data on trends, competitors, SEO, content, UX, and design to enhance the site",
    key: "list-research",
    color: "purple1",
  },
  {
    icon: MailCheck,
    title: "B2B-Email",
    detailPath: "/kpo-services/b2b-email",
    description: "Connecting businesses through impactful emails",
    key: "b2b-email",
    color: "purple2",
  },
];

export const RPOSERVICES = [
  {
    icon: ListOrdered,
    title: "Number Gathering",
    detailPath: "/rpo-services/number-gathering",
    description: "Expertly gathering numbers for informed decisions.",
    key: "number-gathering",
    color: "purple1",
  },
  {
    icon: Lightbulb,
    title: "Talent Mapping",
    detailPath: "/rpo-services/talent-mapping",
    description: "Strategically mapping talent for the right fit.",
    key: "talent-mapping",
    color: "purple2",
  },
  {
    icon: Search,
    title: "Talent Sourcing",
    detailPath: "/rpo-services/talent-sourcing",
    description: "Connecting the right talent with the right opportunity.",
    key: "talent-sourcing",
    color: "purple1",
  },
  {
    icon: ChartColumnBig,
    title: "Talent Insight & Intelligence",
    detailPath: "/rpo-services/talent-insight",
    description: "Unlocking talent insights for smarter decisions.",
    key: "talent-insight",
    color: "purple2",
  },
  {
    icon: UsersRound,
    title: "Diversity Hiring",
    detailPath: "/rpo-services/diversity-hiring",
    description: "Fostering diverse teams for stronger innovation.",
    key: "diversity-hiring",
    color: "purple1",
  },
  {
    icon: BriefcaseBusiness,
    title: "Executive Search Support",
    detailPath: "/rpo-services/executive-search-support",
    description: "Empowering executive search with tailored support.",
    key: "executive-search-support",
    color: "purple2",
  },
  {
    icon: UserRoundPlus,
    title: "Talent Pipeline",
    detailPath: "/rpo-services/talent-pipeline",
    description: "Building a pipeline of top-tier talent for future success.",
    key: "talent-pipeline",
    color: "purple1",
  },
  {
    icon: FileText,
    title: "Recruitment Services",
    detailPath: "/rpo-services/recruitment-services",
    description: "Connecting the right talent with the right opportunities.",
    key: "recruitment-services",
    color: "purple2",
  },
  {
    icon: FilePlus,
    title: "Talent Pooling",
    detailPath: "/rpo-services/talent-pooling",
    description: "Creating a pool of top talent for future growth.",
    key: "talent-pooling",
    color: "purple1",
  },
  {
    icon: User,
    title: "Admin Support",
    detailPath: "/rpo-services/admin-support",
    description: "Efficient admin support to streamline your operations.",
    key: "admin-support",
    color: "purple2",
  },
];

export const BPOSERVICES = [
  {
    key: "customer-support",
    title: "Customer Support",
    description: "24/7 voice, chat, email & WhatsApp support.",
    icon: Headset,
    color: "purple1",
  },
  {
    key: "call-center",
    title: "Inbound & Outbound Calls",
    description: "Professional call center operations.",
    icon: Phone,
    color: "purple2",
  },
  {
    key: "multichannel",
    title: "Multichannel Communication",
    description: "Chat, social, email & messaging platforms.",
    icon: MessageSquare,
    color: "purple1",
  },
  {
    key: "process-management",
    title: "Process Management",
    description: "End-to-end backend & operations handling.",
    icon: Settings,
    color: "purple2",
  },
  {
    key: "order-billing",
    title: "Order & Billing Management",
    description: "Accurate order tracking & billing workflows.",
    icon: CreditCard,
    color: "purple1",
  },
  {
    key: "data-ops",
    title: "Data Processing",
    description: "Data entry, verification & validation.",
    icon: FileCheck,
    color: "purple2",
  },
  {
    key: "crm-ops",
    title: "CRM Operations",
    description: "CRM updates, workflow & reporting.",
    icon: Layers,
    color: "purple1",
  },
  {
    key: "qa-monitoring",
    title: "QA & Performance Monitoring",
    description: "Quality assurance & KPI tracking.",
    icon: BarChart3,
    color: "purple2",
  },
  {
    key: "appointments",
    title: "Appointment Scheduling",
    description: "Lead follow-ups & scheduling.",
    icon: CalendarClock,
    color: "purple1",
  },
  {
    key: "compliance",
    title: "Compliance & Security",
    description: "Secure & compliant operations.",
    icon: ShieldCheck,
    color: "purple2",
  },
];

export const CRMSERVICES = [
  {
    key: "custom-crm",
    title: "Custom CRM Systems",
    description: "Fully customizable CRM platforms.",
    icon: Database,
    color: "purple1",
  },
  {
    key: "automation",
    title: "Workflow Automation",
    description: "Automate sales, HR & admin workflows.",
    icon: Workflow,
    color: "purple2",
  },
  {
    key: "ai-tools",
    title: "AI Business Tools",
    description: "AI-powered tools for smarter decisions.",
    icon: Brain,
    color: "purple1",
  },
  {
    key: "bots",
    title: "AI Bots & Assistants",
    description: "Chatbots & AI assistants for ops.",
    icon: Bot,
    color: "purple2",
  },
  {
    key: "analytics",
    title: "Analytics & Dashboards",
    description: "Real-time reports & insights.",
    icon: LineChart,
    color: "purple1",
  },
  {
    key: "performance",
    title: "Performance Monitoring",
    description: "Track efficiency & system health.",
    icon: Gauge,
    color: "purple2",
  },
  {
    key: "integrations",
    title: "System Integrations",
    description: "WhatsApp, Email, LinkedIn & more.",
    icon: Blocks,
    color: "purple1",
  },
  {
    key: "scalable-tech",
    title: "Scalable Architecture",
    description: "Cloud-ready, secure & scalable.",
    icon: Cpu,
    color: "purple2",
  },
  {
    key: "fast-deploy",
    title: "Rapid Deployment",
    description: "Fast setup & rollout.",
    icon: Zap,
    color: "purple1",
  },
];

export const CompanyDropdownItems = [
  {
    title: "Why Us",
    href: "/why-us",
  },
  {
    title: "Company Overview",
    href: "/company-overview",
  },
];

export const ServicesDropdownItems = [
  {
    title: "Business Intelligence & Research Solutions",
    href: "/kpo-services",
  },
  {
    title: "Talent Acquisition & Recruitment Solutions",
    href: "/rpo-services",
  },
  {
    title: "Customer Support & Process Management",
    href: "/bpo-services",
  },
  {
    title: "CRM, Automation & AI Tools Developmen",
    href: "/crm-services",
  },
];
